spring:
  application:
    name: Swagger_jpa

springdoc:
  api-docs:
    title: PRODUCTS
    description: CRUD PRODUCTS
    servers:
      - url: http://localhost:8080		
# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    # (this is just an example, not intended to be a production configuration)
